version: '3.7'
services:
  el_1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.1
    environment:
    - cluster.name=docker-cluster
    - xpack.security.enabled=false
    - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
    - 9200:9200
    - 9300:9300
    volumes:
    - ./el_1:/data
  php_l10:
    build:       Docker/PHP
    working_dir: /var/www/app
    volumes:
    - ./app:/var/www/app
